### ISSUE TITLE
issue when do : npx hardhat run ./scripts/deploy.js --network localhost

### ISSUE THREAD

**Issue by Amani-noui** [dappuniversity/millow#23]
i got this , give me a suggestion , or a solution 
PS C:\Users\User\millow> npx hardhat run ./scripts/deploy.js --network localhost
HardhatError: HH108: Cannot connect to the network localhost.
Please make sure your node is running, and check your internet connection and networks config
    at HttpProvider._fetchJsonRpcResponse (C:\Users\User\millow\node_modules\hardhat\src\internal\core\providers\http.ts:223:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HttpProvider.request (C:\Users\User\millow\node_modules\hardhat\src\internal\core\providers\http.ts:87:29)
    at EthersProviderWrapper.send (C:\Users\User\millow\node_modules\@nomiclabs\hardhat-ethers\src\internal\ethers-provider-wrapper.ts:13:20)
    at getSigners (C:\Users\User\millow\node_modules\@nomiclabs\hardhat-ethers\src\internal\helpers.ts:45:20)
    at main (C:\Users\User\millow\scripts\deploy.js:15:46)

    Caused by: Error: connect ECONNREFUSED 127.0.0.1:8545
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)

**Comment by Secret1007** [comment]
![image](https://github.com/user-attachments/assets/7c7bdd08-bf61-4a0d-adc5-483c7a639e51)
Here are some tips: maybe you should run npx hardhat node first.

**Comment by hr188** [comment]
Can you help me run this project ?
